name: Test LINE Push

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v5
　　　 - name: Install Python packages
        run: pip install requests feedparser openai
      - name: Run script
        run: python main.py
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
